# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('ubicacion', models.TextField()),
                ('ancho_de_banda', models.IntegerField()),
                ('slug_celula', models.SlugField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20)),
                ('distribuidor', models.CharField(max_length=20)),
                ('ancho_de_banda', models.IntegerField()),
                ('slug_linea', models.SlugField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedLan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_red', models.GenericIPAddressField()),
                ('ip_host_inicial', models.GenericIPAddressField()),
                ('ip_host_final', models.GenericIPAddressField()),
                ('ip_mascara_de_red', models.GenericIPAddressField()),
                ('celula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.Celula')),
            ],
        ),
        migrations.AddField(
            model_name='celula',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infraestructura.Linea'),
        ),
    ]
