# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=10)),
                ('mail', models.EmailField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=5)),
                ('numero_exterior', models.CharField(max_length=5)),
                ('numero_interior', models.CharField(blank=True, max_length=5, null=True)),
                ('colonia', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('codigo_postal', models.CharField(max_length=5)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
    ]
